name: gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.8
  - pip
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - wandb
  - pip:
    # - submodules/diff-gaussian-rasterization
    - submodules/simple-knn